# services:
#   db:
#     #container_name: data
#     image: "postgres:16"
#     environment:
#       POSTGRES_USER: risshikaa
#       POSTGRES_PASSWORD: masters123
#       POSTGRES_DB: shelter

#     volumes:
#       - db_data:/var/lib/postgresql/data
#       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#     ports:
#       - "5432:5432"
#   etl:
#     #container_name: etl_demo
#     build: .
#     command: https://shelterdata.s3.amazonaws.com/shelter1000.csv
#     depends_on:
#      - db
    
# volumes:
#   db_data:

services:
  database:
    image: "postgres:16"
    # # container_name: postgres_test
    environment:
      POSTGRES_USER: risshikaa
      POSTGRES_PASSWORD: masters123
      POSTGRES_DB: shelter
    volumes:
      - database_data:/var/lib/postgresql/data  
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  etl:
    build: .
    command: https://shelterdata.s3.amazonaws.com/shelter1000.csv
    depends_on:
      - database   
volumes:
  database_data: